openapi: 3.0.3
info:
  title: Products API
  version: 1.0.0
  description: CRUD endpoints for ScrapedProduct entity

paths:
  /products:
    get:
      summary: List all products
      tags: [Products]
      parameters:
        - name: page
          in: query
          schema:
            type: integer
            default: 1
            minimum: 1
        - name: limit
          in: query
          schema:
            type: integer
            default: 10
            minimum: 1
            maximum: 100
        - name: status
          in: query
          schema:
            $ref: '#/components/schemas/ProductStatus'
        - name: botId
          in: query
          schema:
            type: string
            format: uuid
        - name: minDiscount
          in: query
          schema:
            type: integer
            minimum: 0
            maximum: 100
        - name: search
          in: query
          schema:
            type: string
          description: Search in product title
      responses:
        '200':
          description: Paginated list of products
          content:
            application/json:
              schema:
                allOf:
                  - $ref: '#/components/schemas/PaginatedResponse'
                  - type: object
                    properties:
                      data:
                        type: array
                        items:
                          $ref: '#/components/schemas/Product'

    post:
      summary: Create a product manually
      tags: [Products]
      description: Admin endpoint for manual product creation
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateProductDto'
      responses:
        '201':
          description: Product created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiResponse'
        '400':
          description: Validation error
        '409':
          description: ASIN already exists

  /products/{id}:
    parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
          format: uuid

    get:
      summary: Get a product by ID
      tags: [Products]
      responses:
        '200':
          description: Product details
          content:
            application/json:
              schema:
                allOf:
                  - $ref: '#/components/schemas/ApiResponse'
                  - type: object
                    properties:
                      data:
                        $ref: '#/components/schemas/Product'
        '404':
          description: Product not found

    patch:
      summary: Update a product
      tags: [Products]
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateProductDto'
      responses:
        '200':
          description: Product updated
          content:
            application/json:
              schema:
                allOf:
                  - $ref: '#/components/schemas/ApiResponse'
                  - type: object
                    properties:
                      data:
                        $ref: '#/components/schemas/Product'
        '404':
          description: Product not found

    delete:
      summary: Delete a product
      tags: [Products]
      responses:
        '200':
          description: Product deleted
        '404':
          description: Product not found

  /products/{id}/approve:
    parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
          format: uuid

    post:
      summary: Approve a product
      tags: [Products]
      responses:
        '200':
          description: Product approved
          content:
            application/json:
              schema:
                allOf:
                  - $ref: '#/components/schemas/ApiResponse'
                  - type: object
                    properties:
                      data:
                        $ref: '#/components/schemas/Product'
        '404':
          description: Product not found
        '400':
          description: Product not in PENDING_APPROVAL status

  /products/{id}/reject:
    parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
          format: uuid

    post:
      summary: Reject a product
      tags: [Products]
      responses:
        '200':
          description: Product rejected
          content:
            application/json:
              schema:
                allOf:
                  - $ref: '#/components/schemas/ApiResponse'
                  - type: object
                    properties:
                      data:
                        $ref: '#/components/schemas/Product'
        '404':
          description: Product not found
        '400':
          description: Product not in PENDING_APPROVAL status

  /products/bulk/approve:
    post:
      summary: Bulk approve products
      tags: [Products]
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - ids
              properties:
                ids:
                  type: array
                  items:
                    type: string
                    format: uuid
      responses:
        '200':
          description: Products approved
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                  data:
                    type: object
                    properties:
                      updated:
                        type: integer
                      skipped:
                        type: integer

components:
  schemas:
    ProductStatus:
      type: string
      enum: [PENDING_APPROVAL, APPROVED, REJECTED, POSTED]

    Product:
      type: object
      properties:
        id:
          type: string
          format: uuid
        asin:
          type: string
        title:
          type: string
        currentPrice:
          type: number
          format: float
        originalPrice:
          type: number
          format: float
        discountPercentage:
          type: integer
        imageUrl:
          type: string
          format: uri
        productUrl:
          type: string
          format: uri
        status:
          $ref: '#/components/schemas/ProductStatus'
        botId:
          type: string
          format: uuid
          nullable: true
        bot:
          type: object
          nullable: true
          properties:
            id:
              type: string
              format: uuid
            name:
              type: string
        foundAt:
          type: string
          format: date-time
        expiresAt:
          type: string
          format: date-time
          nullable: true

    CreateProductDto:
      type: object
      required:
        - asin
        - title
        - currentPrice
        - originalPrice
        - discountPercentage
        - imageUrl
        - productUrl
      properties:
        asin:
          type: string
        title:
          type: string
        currentPrice:
          type: number
          minimum: 0
        originalPrice:
          type: number
          minimum: 0
        discountPercentage:
          type: integer
          minimum: 0
          maximum: 100
        imageUrl:
          type: string
          format: uri
        productUrl:
          type: string
          format: uri
        botId:
          type: string
          format: uuid
        expiresAt:
          type: string
          format: date-time

    UpdateProductDto:
      type: object
      properties:
        title:
          type: string
        currentPrice:
          type: number
          minimum: 0
        originalPrice:
          type: number
          minimum: 0
        discountPercentage:
          type: integer
          minimum: 0
          maximum: 100
        imageUrl:
          type: string
          format: uri
        productUrl:
          type: string
          format: uri
        status:
          $ref: '#/components/schemas/ProductStatus'
        expiresAt:
          type: string
          format: date-time
          nullable: true

    PaginatedResponse:
      type: object
      properties:
        success:
          type: boolean
          example: true
        meta:
          type: object
          properties:
            total:
              type: integer
            page:
              type: integer
            limit:
              type: integer
            totalPages:
              type: integer

    ApiResponse:
      type: object
      properties:
        success:
          type: boolean
          example: true
        data:
          type: object

    ApiError:
      type: object
      properties:
        success:
          type: boolean
          example: false
        error:
          type: object
          properties:
            code:
              type: string
            message:
              type: string
